# Generated by Django 5.2.5 on 2025-08-07 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique client identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Client business name', max_length=255)),
                ('email', models.EmailField(help_text='Client contact email', max_length=254, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of the client's business")),
                ('api_key', models.CharField(db_index=True, help_text='Public API key', max_length=255, unique=True)),
                ('api_secret_hash', models.CharField(help_text='Hashed API secret for verification', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], default='active', help_text='Client account status', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', help_text='Client subscription plan', max_length=20)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='API calls allowed per minute')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000, help_text='API calls allowed per hour')),
                ('rate_limit_per_day', models.PositiveIntegerField(default=10000, help_text='API calls allowed per day')),
                ('webhook_url', models.URLField(blank=True, help_text='Client webhook URL for notifications', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook signature verification', max_length=255)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Client account balance', max_digits=15)),
                ('total_transactions', models.PositiveIntegerField(default=0, help_text='Total number of transactions')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, help_text='Total transaction volume', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_api_call', models.DateTimeField(blank=True, help_text='Timestamp of last API call', null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Associated Django user account', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_enabled', models.BooleanField(default=True, help_text='Enable MPesa payments for this client')),
                ('mpesa_shortcode', models.CharField(blank=True, help_text="Client's MPesa business shortcode", max_length=10)),
                ('mpesa_passkey', models.TextField(blank=True, help_text='Encrypted MPesa passkey')),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum transaction amount', max_digits=10)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=100000.0, help_text='Maximum transaction amount', max_digits=10)),
                ('daily_transaction_limit', models.DecimalField(decimal_places=2, default=1000000.0, help_text='Daily transaction limit', max_digits=15)),
                ('email_notifications', models.BooleanField(default=True, help_text='Send email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Send SMS notifications')),
                ('webhook_notifications', models.BooleanField(default=True, help_text='Send webhook notifications')),
                ('require_signature', models.BooleanField(default=True, help_text='Require request signature verification')),
                ('signature_algorithm', models.CharField(default='hmac-sha256', help_text='Signature algorithm', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Configuration',
                'verbose_name_plural': 'Client Configurations',
                'db_table': 'client_configurations',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint accessed', max_length=255)),
                ('method', models.CharField(help_text='HTTP method used', max_length=10)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent')),
                ('request_size', models.PositiveIntegerField(default=0, help_text='Request size in bytes')),
                ('response_size', models.PositiveIntegerField(default=0, help_text='Response size in bytes')),
                ('response_time', models.PositiveIntegerField(default=0, help_text='Response time in milliseconds')),
                ('status_code', models.PositiveIntegerField(help_text='HTTP response status code')),
                ('error_message', models.TextField(blank=True, help_text='Error message if any')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, help_text='Unique request identifier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='clients.client')),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'db_table': 'api_usage_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['client', 'timestamp'], name='api_usage_l_client__0b7fa9_idx'), models.Index(fields=['endpoint', 'timestamp'], name='api_usage_l_endpoin_bc57dc_idx'), models.Index(fields=['status_code', 'timestamp'], name='api_usage_l_status__fd4290_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='API key name/description', max_length=255)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('api_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('api_secret_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=list, help_text='List of allowed permissions/scopes')),
                ('rate_limit_per_minute', models.PositiveIntegerField(blank=True, help_text='Override client rate limit per minute', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='API key expiration date', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client API Key',
                'verbose_name_plural': 'Client API Keys',
                'db_table': 'client_api_keys',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'name', 'environment')},
            },
        ),
    ]
